CREATE TABLE IF NOT EXISTS `shipments` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `inbound_id` INT NOT NULL,
    `status` VARCHAR(50) NOT NULL,
    `shipper_name` VARCHAR(128) NOT NULL,
    `shipper_phone_number` VARCHAR(15) NOT NULL,
    `receiver_name` VARCHAR(255) NOT NULL,
    `receiver_phone_number` VARCHAR(15) NOT NULL,
    `receiver_state` VARCHAR(255) NOT NULL,
    `receiver_city` VARCHAR(128) NOT NULL,
    `receiver_postal_code` VARCHAR(10) NOT NULL,
    `receiver_address` VARCHAR(128) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `length` DECIMAL(10, 2) NOT NULL,
    `width` DECIMAL(10, 2) NOT NULL,
    `height` DECIMAL(10, 2) NOT NULL,
    `service` VARCHAR(50) NOT NULL,
    `created_at` DATE NOT NULL,
    `updated_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`)
);